### ISSUE TITLE
Token rotation 

### ISSUE THREAD

**Issue by Immortalin** [seratch/slack-edge#1]
Does this library support token rotation?

**Comment by seratch** [comment]
Hi @Immortalin, thanks for writing in. It's not yet supported but I will add the support soon!

**Comment by seratch** [comment]
This is now supported on the slack-cloudflare-workers package side. If someone would like to enable it for other platforms, checking the code could be helpful to learn how to do so: https://github.com/seratch/slack-cloudflare-workers/blob/main/src/kv-installation-store.ts
