### ISSUE TITLE
Custom Page Redirection After OAuth in SlackOAuthApp

### ISSUE THREAD

**Issue by abc123931** [seratch/slack-edge#2]
I am trying to modify the behavior of the SlackOAuthApp. 
Specifically, after redirecting from '/slack/install' to '/slack/oauth_redirect', I want to display an original page or redirect to another page instead of showing the default renderCompletionPage. 
Is there any way to accomplish this?

**Comment by seratch** [comment]
Hi @abc123931, thanks for submitting this issue! Right now, this framework does not provide a way to customize the endpoint behaviors. I will add the functionalities in the next release!

**Comment by abc123931** [comment]
Hi, thank you for your quick response and willingness to add this functionality to the upcoming release! I'm looking forward to trying out the new feature when it's available.
