### ISSUE TITLE
Interactivity routing support

### ISSUE THREAD

**Issue by t6adev** [seratch/slack-edge#20]
I'm trying it now I realized there is only supported events routing.

https://github.com/seratch/slack-edge/blob/1b7346fb9de21d1bbe6eed351851dd0ada646391/src/app.ts#L529-L534

However, the console has an input field for the interactivity path we have to.

<img width="745" alt="image" src="https://github.com/seratch/slack-edge/assets/6883692/fc685c65-80cd-4ee7-9b7f-edb2396b7792">

But if we set it to the same event_subscriptions path, it seems to work well.

1. What's the correct?
2. Is there no problem with the wired setting?

**Comment by seratch** [comment]
Hi @t6adev, thanks for asking the question. The name "events" might be a little confusing but you can use a single endpoint URL, which is configured as "routes.events" for all Request URLs in the Slack app configuration page.
