### ISSUE TITLE
Unexpected Behavior with SlackOAuthApp's stateStore, onStateValidationError, and callback Functions

### ISSUE THREAD

**Issue by abc123931** [seratch/slack-edge#3]
I have been using the stateStore setting in SlackOAuthApp and noticed some surprising behavior. 

When the consume function returns false, I would expect the `onStateValidationError` function in the oauth options to get executed, which does occur as expected. 

However, the process seems to proceed further than anticipated, and the `callback` function in the oauth options gets executed as well. Is this the intended behavior or could this possibly be a bug?

**Comment by seratch** [comment]
@abc123931 Thanks for reporting this and sorry that you ran into the silly bug 🤦 

I just resolved it and shipped a new pathc version including the change. Note that the fix might miss something because I didn't have time to do manual tests now. Pleaset let me know if the issue still remains.
