### ISSUE TITLE
`actor_id` in ChannelDeletedEvent

### ISSUE THREAD

**Issue by StephenTangCook** [seratch/slack-edge#37]
I have observed that the ChannelDeletedEvent (when a Slack channel is deleted) payload contains `actor_id` for the user that deleted the channel, although this is not doc'd on the [API page](https://api.slack.com/events/channel_deleted). Is this a reliable property?

Example:
```
{
  "channel": "C07QF2RK0FZ",
  "actor_id": "U060JP64TQZ",
  "type": "channel_deleted",
  "event_ts": "1728097096.002700"
}
```

**Comment by seratch** [comment]
Sorry, I overlooked this issue! I will add this property
