### ISSUE TITLE
team_domain_change misspelled

### ISSUE THREAD

**Issue by zhawtof** [seratch/slack-edge#40]
According to this:
https://github.com/seratch/slack-web-api-client/blob/eb3fc27c3ef8d660f121b9e09711ce63c1735dd1/src/manifest/events.ts#L88

the `team_domain_change` event should not contain a `d` at the end, yet it does here. One of these is incorrect.

https://github.com/seratch/slack-edge/blob/844f734b0af70ecfe0b05a49c22f54e51082656d/src/request/payload/event.ts#L877-L878

**Comment by seratch** [comment]
Oh, what an inconsistency of naming! Thanks
