### ISSUE TITLE
SlackOAuthAppOptions with authorizeErrorHandler

### ISSUE THREAD

**Issue by zhawtof** [seratch/slack-edge#46]
This pull request https://github.com/seratch/slack-edge/pull/45 is missing support for `SlackOAuthAppOptions` to override `authorizeErrorHandler`.

https://github.com/seratch/slack-edge/blob/d1fb190c27f9e7ac9d7a49fb3c59f943abe92944/src/oauth-app.ts#L31

**Comment by seratch** [comment]
Oh, thanks for pointing this out! Will resolve this issue quickly
