### ISSUE TITLE
Interruption of Long Responses in Slack App Using Vercel Edge Functions with OpenAI's Chat API

### ISSUE THREAD

**Issue by abc123931** [seratch/slack-edge#5]
Hello,

I'm currently developing a Slack application that mentions and asks questions, receiving responses from ChatGPT. This app is built using Vercel Edge Functions and integrates with OpenAI's Chat API in stream mode. The process involves editing the messages using `chat.update` to create a streaming effect.

However, I'm encountering an issue where the processing of long responses gets interrupted after approximately 30 seconds. This seems to align with the behavior mentioned in [an article](https://zenn.dev/catnose99/scraps/b4752fac25cd92) regarding interruptions in processes handled by `waitUntil`.

I'm seeking advice or potential solutions to prevent this interruption and ensure longer responses are fully processed. Any suggestions or insights into this matter would be greatly appreciated.

Thank you for your assistance.

**Comment by abc123931** [comment]
Hi @seratch 
Thank you for your response and the effort you put into researching this issue. 
I will consider alternative approaches.

**Comment by seratch** [comment]
Since this project does not have action items for this topic, let me close this issue now. If the platform offers an option to extend the time duration in the future, we are happy to support the use case!
