### ISSUE TITLE
setting up an oauth flow - example needed

### ISSUE THREAD

**Issue by amithalb** [seratch/slack-edge#51]
Hi,

Thank you for building this library! 🙏 

Is there a reference of any kind on how to set up a an oauth flow using slack-edge?

I am making slow progress in figuring it out from the code, but even a very simple example of how this thing works together (...even how to initialize SlackOAuthApp properly) would make my life much easier.

I guess a more general question would be - is this available documentation for this repo outside of the README and the example at https://github.com/seratch/slack-edge-app-template (which was incredibly helpful) ?

Thanks again!

**Comment by leo-paz** [comment]
@amithalb Can you provide any resources on what helped you set it up?

**Comment by amithalb** [comment]
Yes! I just needed a very simple example of how it works, eventually figured it out, here's what I did.

For context (this was the part that confused me) - I created a **shared** app initialization module, used by route handlers in `/slack/installation`, `/slack/oauth_redirect` and `/slack/events`. 

I use next.js, and the initialization code in `/installation` and `/oauth_redirect` looks like this:
```
import { slackApp } from '../slack-oauth-shared'
import { waitUntil } from '@vercel/functions'

export async function GET(req: Request) {
  return await slackApp.run(req, { waitUntil })
}
```

and in `/events` i also initialize event handlers (same as a non-oauth app).

Anyway the shared file (`slack-oauth-shared.ts`) looks something like this:

``` typescript
import { InstallationStore, SlackOAuthApp, SlackOAuthEnv } from 'slack-edge'
import { and, eq } from 'drizzle-orm'

const installationStore: InstallationStore<SlackOAuthEnv> = {
  save: async installation => {
    
      // persist installation to db, unique index on teamId and appId, on conflict (re-installation) - update
      
      // use the bot token and a slack client to send a welcome message
  
  },

  findBotInstallation: async req => {
    // find installation by teamId and appId, return it
  },

  findUserInstallation: async req => {
    // I used the same logic as findBotInstallation
    // since we're storing one installation per team
    return installationStore.findBotInstallation(req)
  },

  deleteAll: async () => {
    // delete all installations
  },

  deleteBotInstallation: async req => {
    // delete installation by teamId and appId
  },

  deleteUserInstallation: async req => {
    // I used the same logic as deleteBotInstallation
    return installationStore.deleteBotInstallation(req)
  },

  toAuthorize: () => async req => {
    const teamId = req.context.teamId

    // find installation by teamId and return it
  }
}

// validate environment variables...

export const slackApp = new SlackOAuthApp({
  env: {
    SLACK_CLIENT_ID: process.env.SLACK_CLIENT_ID!,
    SLACK_CLIENT_SECRET: process.env.SLACK_CLIENT_SECRET!,
    SLACK_SIGNING_SECRET: process.env.SLACK_SIGNING_SECRET!,
    SLACK_BOT_SCOPES: process.env.SLACK_BOT_SCOPES!
  } as SlackOAuthEnv,

  installationStore,
  routes: {
    events: '/api/slack/events',
    oauth: {
      start: '/api/slack/install',
      callback: '/api/slack/oauth_redirect'
    }
  },
  oauth: {
    afterInstallation: async args => {
    // log non-sensitive info
    }
  }
})


```

Hope this helps!

**Comment by leo-paz** [comment]
helpful! thanks @amithalb

**Comment by leo-paz** [comment]
@amithalb I'm wondering if you had to pass any metadata as part of the installation to link the installation to an organization in your own database? I see examples in the `node-slack-sdk` for passing metadata when generating an install url but I don't see how that would be kept in any `metadata` field in the `slack-edge` package

**Comment by seratch** [comment]
slack-edge doesn't support metadata parameter, so you don't need to worry about it.

**Comment by leo-paz** [comment]
@seratch in that case what would be the best way to capture the organization id from the auth session that initialized the "Add to Slack" flow so I can use it in my `installationStore`

**Comment by seratch** [comment]
You can use browser cookies to store the value and access them in these callbacks: https://github.com/seratch/slack-edge/blob/main/src/oauth-app.ts#L57
